#!/bin/bash
# Generate the key material this example needs. Run once, before `docker compose up`.
#
# Nothing cryptographic is committed — a private key in a public repository is
# not a secret, and committing one teaches the wrong habit. Everything produced
# here is throwaway and local; regenerate it freely.
#
# Produces:
#   authelia/oidc.issuer.key  RSA key Authelia signs OIDC tokens with, and whose
#                             public half it publishes at /jwks.json. MUST be
#                             asymmetric: a provider on a symmetric key serves an
#                             EMPTY key set and nothing can verify a token.
#   certs/ca.pem, ca.key      A local certificate authority...
#   certs/authelia.crt/.key   ...and the TLS certificate it signs for Authelia,
#                             which refuses to serve OpenID Connect over http.
#   .env                      Random secrets compose passes to the containers:
#                             Authelia's session/storage/HMAC keys, and the MCP
#                             server's TOKEN_ENCRYPTION_KEY (which encrypts
#                             stored credentials, so it is real key material and
#                             not something to copy from an example).
set -euo pipefail
cd "$(dirname "$0")"

# Create every file owner-only from the start. The chmod at the end would
# otherwise leave a window: a run interrupted between the CA and the TLS
# certificate leaves private keys at the default umask until the next --force
# run completes. Narrowing that window is not as good as not having one.
umask 077

OUTPUTS=(
    authelia/oidc.issuer.key
    certs/ca.key certs/ca.pem
    certs/authelia.key certs/authelia.crt
    .env
)

# Check every output, not just a couple: a run interrupted midway leaves some
# present and some missing, and short-circuiting on a partial set would hand
# you a stack that fails much later with a confusing error.
missing=0
for f in "${OUTPUTS[@]}"; do
    [[ -f "$f" ]] || missing=1
done
if [[ $missing -eq 0 && "${1:-}" != "--force" ]]; then
    echo "Already generated. Re-run with --force to replace."
    exit 0
fi

# `openssl req -section` is OpenSSL 3.x only — LibreSSL, which is still what
# /usr/bin/openssl is on macOS, does not have it. Without this check the script
# fails with a bare "unknown option" that gives no hint the problem is the
# openssl build rather than the config.
if ! openssl req -help 2>&1 | grep -q -- '-section'; then
    echo "ERROR: this script needs OpenSSL 3.x; '$(openssl version)' has no 'req -section'." >&2
    echo "       On macOS: brew install openssl, then put it first on PATH:" >&2
    echo '         export PATH="$(brew --prefix openssl)/bin:$PATH"' >&2
    exit 1
fi

echo "==> OIDC token signing key (RS256)"
openssl genrsa -out authelia/oidc.issuer.key 2048 2>/dev/null

echo "==> Local certificate authority"
openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -config certs/openssl.cnf -extensions v3_ca \
    -keyout certs/ca.key -out certs/ca.pem 2>/dev/null

echo "==> TLS certificate for auth.astrolabe.test"
openssl req -newkey rsa:2048 -nodes \
    -config certs/openssl.cnf -section server_req \
    -keyout certs/authelia.key -out certs/authelia.csr 2>/dev/null

openssl x509 -req -in certs/authelia.csr -days 3650 \
    -CA certs/ca.pem -CAkey certs/ca.key -CAcreateserial \
    -extfile certs/openssl.cnf -extensions v3_server \
    -out certs/authelia.crt 2>/dev/null

rm -f certs/authelia.csr certs/ca.srl

echo "==> Random secrets (.env)"
rand() { openssl rand -base64 "${1:-48}" | tr -d '\n=' | tr '+/' '-_'; }
{
    echo "# Generated by ./generate-secrets.sh — git-ignored, throwaway, local only."
    echo "# Compose reads this file automatically."
    echo
    echo "# Authelia reads these as overrides for session.secret,"
    echo "# storage.encryption_key, identity_validation.reset_password.jwt_secret"
    echo "# and identity_providers.oidc.hmac_secret."
    echo "AUTHELIA_SESSION_SECRET=$(rand)"
    echo "AUTHELIA_STORAGE_ENCRYPTION_KEY=$(rand)"
    echo "AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=$(rand)"
    echo "AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET=$(rand 32)"
    echo
    echo "# Encrypts the credentials the MCP server stores at rest. Must be a"
    echo "# 32-byte url-safe base64 key (Fernet)."
    echo "TOKEN_ENCRYPTION_KEY=$(openssl rand -base64 32 | tr '+/' '-_')"
} > .env

# umask 077 above already created these owner-only; this is belt-and-braces for
# a re-run over files from an older revision of this script. The containers read
# them through bind mounts as the invoking user's files, so owner-only is enough
# on a normal single-user host.
chmod 600 authelia/oidc.issuer.key certs/authelia.key certs/ca.key .env
# The certificate and CA are public halves — readable so you can inspect them.
chmod 644 certs/ca.pem certs/authelia.crt

echo
echo "Done. Subject alternative names on the Authelia certificate:"
openssl x509 -in certs/authelia.crt -noout -ext subjectAltName
echo
echo "Next: docker compose up -d"
