#!/bin/bash
# Generate the key material this example needs. Run once, before `docker compose up`.
#
# Unlike the Authelia example there are no certificates to make — authentik
# serves OIDC over plain http and generates its own token-signing keypair
# internally on first start. Only the two process-level secrets are needed.
#
# Produces:
#   .env  AUTHENTIK_SECRET_KEY   signs authentik's sessions and cookies
#         TOKEN_ENCRYPTION_KEY   encrypts the credentials the MCP server stores
#                                at rest (Fernet, 32-byte url-safe base64)
#
# Both are real key material, which is why they are generated here and
# git-ignored rather than committed for you to copy into something real.
set -euo pipefail
cd "$(dirname "$0")"

# Create .env owner-only from the start. A chmod afterwards would leave the
# secrets on disk at the default umask (022/002 on many hosts) for the moment
# between the redirect writing them and the chmod running. Both values here
# sign or encrypt something, so that window is worth removing rather than
# narrowing. Same reasoning as the Authelia example's script.
umask 077

if [[ -f .env && "${1:-}" != "--force" ]]; then
    echo "Already generated (.env). Re-run with --force to replace."
    exit 0
fi

{
    echo "# Generated by ./generate-secrets.sh — git-ignored, throwaway, local only."
    echo "# Compose reads this file automatically."
    echo
    echo "AUTHENTIK_SECRET_KEY=$(openssl rand -base64 48 | tr -d '\n=' | tr '+/' '-_')"
    # Note the missing `tr -d '='` compared to the line above: this one is a
    # Fernet key, which is exactly 32 bytes of url-safe base64 *with* its single
    # padding character. Stripping it makes the MCP server reject the key.
    echo "TOKEN_ENCRYPTION_KEY=$(openssl rand -base64 32 | tr '+/' '-_')"
} > .env

# umask 077 above already created it owner-only; this is belt-and-braces for a
# re-run over a .env left by an older revision of this script.
chmod 600 .env

echo "Wrote .env"
echo
echo "Next: docker compose up -d"
